# NumPy (Numerical Python)
NumPy is an open-source Python library used for numerical computing, particularly for working with arrays, matrices, and high-level mathematical functions.

It provides:
* A powerful N-dimensional array object (ndarray)
* Broadcasting capabilities for arithmetic operations
* Mathematical, logical, and statistical functions on arrays
* Tools for linear algebra, Fourier transforms, and random number generation
* Integration with C/C++/Fortran code for performance



## Key points
* NumPy arrays are homogeneous (all elements have the same data type)
* Much faster and more efficient than Python lists for large-scale numerical data
* Forms the foundation for scientific computing in Python

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Create Array
* All elements in a NumPy array have the same data type (e.g., all integers, all floats).
* Can be 1D, 2D, 3D, or higher dimensions.
* Supports vectorized operations — you can perform arithmetic on the whole array at once.
* It is the core data structure for numerical computing in Python.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
my_list = [1,2,3,4,5,6]
print(np.array(my_list))
print(type(my_list))

[1 2 3 4 5 6]
<class 'list'>


In [ ]:
my_list = ["Ahmad", "Amjad","Talha"]
arr_from_list = np.array(my_list)
print(arr_from_list)
print(type(my_list))
print(type(arr_from_list))

['Ahmad' 'Amjad' 'Talha']
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Changing Datatype


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(arr)
arr = arr.astype('float32')
print(arr.dtype)
print(arr)

int64
[1 2 3 4 5]
float32
[1. 2. 3. 4. 5.]


# Array Functions




## arange()
Create array with a range of numbers

In [ ]:
arr = np.arange(1,11)
print(arr)
arr1 = np.arange(1,11,2)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


## zeros() and ones()
Create an array filled with zeros and ones

In [ ]:
# zeros
arr1 = np.zeros((2,3)) # 2 rows , 3 columns
print(arr1)
#  ones
arr0 = np.ones((2,2))
print(arr0)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


## linespace()
Create an array of evenly spaced numbers


In [ ]:
arr = np.linspace(0,1,5) # 5 numbers from 0 to 1
print(arr)

[0.   0.25 0.5  0.75 1.  ]


## reshape()
change the shape of an array

In [ ]:
arr = np.arange(6)
print(arr)
# reshape
arr2 = arr.reshape((2,3))
print(arr2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## append()
Add the element to an array(return the new array)

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
# add the element
arr1 = np.arange(8)
print(arr1)
apend_arr = np.append(arr,arr1)
print("Appended array: ",apend_arr)

[1 2 3 4]
[0 1 2 3 4 5 6 7]
Appended array:  [1 2 3 4 0 1 2 3 4 5 6 7]


## insert()
Insert element add specific index

In [ ]:
arr = np.arange(6)
print(arr)
new_arr = np.insert(arr,1,10) # insert 10 at index 10
print("element added: ",new_arr)

[0 1 2 3 4 5]
element added:  [ 0 10  1  2  3  4  5]


## delete()
Delete element at specific index

In [ ]:
arr = np.arange(7)
print(arr)
new_arr = np.delete(arr,2) # remove element at index 2
print(new_arr)

[0 1 2 3 4 5 6]
[0 1 3 4 5 6]


# Array Attributes


## .shape
return the dimension(number of rows and columns)

In [ ]:
arr = np.arange(6,dtype=int)
print(arr.shape)
arr1 = np.arange(6).reshape(2,3)
print(arr1)
print(arr1.shape)

(6,)
[[0 1 2]
 [3 4 5]]
(2, 3)


## .ndim
Return the number of dimensioin

In [ ]:
print("number of dimensions in arr1: ",arr1.ndim)

number of dimensions in arr1:  2


## .size
Retunr the count of number of elements in array

In [ ]:
arr = np.arange(6).reshape(2,3)
print(arr)
print(arr.size)

[[0 1 2]
 [3 4 5]]
6


## .dtype
Tell the data type of elements in array

In [ ]:
arr = np.array([1,2,3,4], dtype=float)
print(arr.dtype)


float64


## .itemsize
Memory size(in bytes) of one element

In [ ]:
arr = np.array([4,5,6,7])
print("size in bytes for each element: ",arr.itemsize)
print("data type of element: ", arr.dtype)

size in bytes for each element:  8
data type of element:  int64


## .nbytes
Total number of bytes used by array in the memory

In [128]:
arr = np.array([1,2,3,4], dtype=np.int64)
print(arr.nbytes)

32


In [131]:
!git clone https://github.com/Amjad-Bin-Aslam/Data-Analysis-Practice.git


Cloning into 'Data-Analysis-Practice'...
remote: Enumerating objects: 229, done.
remote: Counting objects: 100% (229/229), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 229 (delta 75), reused 197 (delta 46), pack-reused 0 (from 0)
Receiving objects: 100% (229/229), 8.49 MiB | 16.40 MiB/s, done.
Resolving deltas: 100% (75/75), done.


In [132]:
!ls



Data-Analysis-Practice	drive  sample_data


In [133]:
%cd Data-Analysis-Practice
!ls



/content/Data-Analysis-Practice
'Excel worksheet'  'Python Basics'   README.md	 SQL_Queries_Practice


In [134]:
%cd Data-Analysis-Practice
!ls



[Errno 2] No such file or directory: 'Data-Analysis-Practice'
/content/Data-Analysis-Practice
'Excel worksheet'  'Python Basics'   README.md	 SQL_Queries_Practice


In [135]:
!git pull

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 2 (delta 1), reused 2 (delta 1), pack-reused 0 (from 0)
Unpacking objects: 100% (2/2), 238 bytes | 238.00 KiB/s, done.
From https://github.com/Amjad-Bin-Aslam/Data-Analysis-Practice
   7d18067..0f9f841  main       -> origin/main
Updating 7d18067..0f9f841
Fast-forward
 .../Basic_Functions_Practice.xlsx                           | Bin
 .../Basic_Math_Formulas.xlsx                                | Bin
 .../Conditional Formatting.xlsx                             | Bin
 .../Data Validation.xlsx                                    | Bin
 .../Data Visualization with charts.xlsx                     | Bin
 .../Date and Time Functions.xlsx                            | Bin
 .../Functions(if,And,OR)_employee_dummy_data.xlsx           | Bin
 .../Functions(sum,,sumif,count,countif, etc.xlsx            | Bin
 {Excel worksheet => 01_Excel worksheet}/Index+Match.

In [136]:
!ls


'01_Excel worksheet'   02_SQL_Queries_Practice	'03_Python Basics'   README.md


In [137]:
!ls

'01_Excel worksheet'   02_SQL_Queries_Practice	'03_Python Basics'   README.md


In [138]:
!git pull

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 1), reused 4 (delta 1), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 319 bytes | 63.00 KiB/s, done.
From https://github.com/Amjad-Bin-Aslam/Data-Analysis-Practice
   0f9f841..b93597c  main       -> origin/main
Updating 0f9f841..b93597c
Fast-forward
 04_numPy/index.js | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 04_numPy/index.js


In [139]:
!ls


'01_Excel worksheet'	  '03_Python Basics'   README.md
 02_SQL_Queries_Practice   04_numPy


In [140]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [ ]:
!mv "/content/drive/MyDrive/Colab Notebooks/" /content/Data-Analysis-Practice/04_numPy/
